pioneer3at:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  
  
  # Position Controllers ---------------------------------------
  p3at_front_left_wheel_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: p3at_front_left_wheel_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
  p3at_front_right_wheel_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: p3at_front_right_wheel_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
  p3at_back_left_wheel_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: p3at_back_left_wheel_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
  p3at_back_right_wheel_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: p3at_back_right_wheel_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
